blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name="Blog"),
    path('category/<int:category_id>/', views.category, name="Category"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', views.add_product, name="add"),
    path('delete/<int:product_id>/', views.delete_product, name="delete"),
    path('subtract/<int:product_id>/', views.subtract_product, name="subtract"),
    path('clean/', views.cart_clean, name="clean"),
]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name="Store"),
]

webProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webProjectApp.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('authentication/', include('authentication.urls')),
    path('shipments/', include('shipments.urls'))
]

store/models.py
from django.db import models

class ProdCategory(models.Model):
    
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        
        verbose_name = "ProdCategory"
        verbose_name_plural = "ProdsCategory"
        
    def __str__(self):
        
        return self.name
    
class Product(models.Model):
    
    name = models.CharField(max_length=50)
    categories = models.ForeignKey(ProdCategory, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="store", null=True, blank=True)
    price = models.FloatField()
    availability = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        
        verbose_name = "Product"
        verbose_name_plural = "Products"

cart/views.py
from django.shortcuts import redirect
from .cart import Cart
from store.models import Product

def add_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.add(product=product)
    return redirect("Store")

def delete_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.delete(product=product)
    return redirect("Store")

def subtract_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.subtract(product=product)
    return redirect("Store")

def cart_clean(request):
    cart = Cart(request)
    cart.clean()
    return redirect("Store")

store/views.py
from django.shortcuts import render
from .models import Product

def store(request):
    products = Product.objects.all()
    return render(request, "store/store.html", {"products":products})

store/templates/cart/widget.html
<table class="table table-bordered" style="color: white;">

    <thead>
        <tr>
            <th colspan="3" class="text-center">Shopping cart</th>
        </tr>
        <tr>
            <th>Product</th>
            <th>Amount</th>
            <th>Sum</th>
        </tr>
    </thead>

    <tbody>

        {% if request.session.cart.items %}

            {% for key, value in request.session.cart.items %}

                <tr class="text-center">
                    <td>{{value.name}}</td>
                    <td>{{value.amount}}</td>
                    <td>
                        <a href="{% url 'cart:add' value.product_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'cart:subtract' value.product_id %}" class="btn btn-sm btn-success">-</a><br/>

                        {{value.price}} $

                    </td>
                </tr>

            {% endfor %}

        {% else %}

            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">No products</div>
                </td>
            </tr>

        {% endif %}

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{total_value}} $ 
            </td>
        </tr>

        {% if request.session.cart.items %}

            <tr>
                <td colspan="3" style="text-align: center;">
                    <a href="#" class="btn btn-success">Buy</a>
                </td>
            </tr>

        {% endif %}

    </tfoot>

</table>